#端口设置
server:
  port: 8080

#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: chenyicai
    password: cyc1234
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 30MB  #设置上传文件的大小
      max-request-size: 30MB


#日志级别（一般设置为INFO）
logging:
  level:
    cn:
      edu:
        guet:
          mapper: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.guet.bean

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
